name: learn-github-actions

on: [push]

jobs:
  Using_python:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 
            3.6
          cache: 
            pip install matplotlib
          architecture: 
            x64
          
